
import Head from "next/head";


export default function SinglePostPage() {

  return (
    <>
      <Head>
        <title>Home \ X</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full border-x border-slate-200 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
          </div>
        </div>
      </main>
    </>
  );
}
